name: ci

on: [push, pull_request, release]

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - name: Clone repo
        uses: actions/checkout@master

      - name: Build container
        run: docker-compose build tests
      
      - name: Run tests
        run: docker-compose run tests